services:
  - type: web
    name: globalscout-backend
    runtime: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: globalscout-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_REFRESH_EXPIRES_IN
        value: 30d
      - key: FRONTEND_URL
        value: https://globalscout-frontend.onrender.com
      - key: MAX_FILE_SIZE
        value: 10485760
      - key: UPLOAD_PATH
        value: /uploads
      - key: BCRYPT_ROUNDS
        value: 12
      - key: SESSION_SECRET
        generateValue: true
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100

databases:
  - name: globalscout-db
    databaseName: globalscout
    user: globalscout
