services:
  - type: web
    name: globalscout-backend
    env: node
    buildCommand: cd backend && npm ci && npx prisma generate && npx prisma migrate deploy
    startCommand: cd backend && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
